<a href="https://colab.research.google.com/github/ginttone/multi_python/blob/master/3_python_language.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# hard coding: 4 * 3 (유연성이 부족한 코딩)
# soft coding:  first=4; second=3; first + second (변수만들어서 연산하는 방법)

In [31]:
import numpy as np

In [32]:
displacement=307.0
horsepower=130.0
weight=3504.0
accel=12.0
cylinders= 8
origin=1

#if cylinders == 3:, origin=1 -> onehot encoding
import numpy as np

if cylinders == 3:
  cylinder=np.array([1,0,0,0,0])
elif cylinders ==4:
  cylinder=np.array([0,1,0,0,0])
elif cylinders == 5:
  cylinder=np.array([0,0,1,0,0])
elif cylinders == 6:
  cylinder=np.array([0,0,0,1,0])
else:
  cylinder=np.array([0,0,0,0,1])

# hard coding
# x_continus =np.array([displacement,horsepower,weight,accel])
# cylinder=np.array([0,0,0,0,1]) # 8 로 지정했을때
# org=np.array([1,0,0]) # 1 로 지정했을때

#soft coding
x_continus =np.array([displacement,horsepower,weight,accel])
org=np.array([1,0,0]) 

In [33]:
cylinder

array([0, 0, 0, 0, 1])

In [34]:
type(x_continus),type(cylinder),type(org)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [35]:
# e는 승수+2(소숫점이 두칸 오른쪽 이동)
# np.concatenate((a, b), axis=None)
result= np.concatenate((x_continus,cylinder,org), axis=None)
result.shape,result 

((12,),
 array([3.070e+02, 1.300e+02, 3.504e+03, 1.200e+01, 0.000e+00, 0.000e+00,
        0.000e+00, 0.000e+00, 1.000e+00, 1.000e+00, 0.000e+00, 0.000e+00]))

- hard coding <br>
result.reshape(1,12)

In [36]:
# soft coding : 열의 값을 유동성있게 주기 ! 
result = result.reshape(-1, result.size)
result, result.shape

(array([[3.070e+02, 1.300e+02, 3.504e+03, 1.200e+01, 0.000e+00, 0.000e+00,
         0.000e+00, 0.000e+00, 1.000e+00, 1.000e+00, 0.000e+00, 0.000e+00]]),
 (1, 12))

# function 의 이해

In [37]:
21 + 14

35

In [38]:
32 + 45

77

first= 32<br>
second = 45<br>
result= first + second<br>
result<br>

In [44]:
#function : 나 잠재적으로 돌아갈 준비 되었어
def sum(): # 이름지정sum 해주고 파라매터() 지정은 자유로이 할 수 있어
  first= 32  
  second = 45
  result= first + second
  return result #나를 호출하면 니가 예상했던대로 동작 후 동작 끝난 결과 값을 줄게

In [45]:
sum()

77

In [64]:
# function에 parameter (f,s) , `?`값 넣어줌
# 변수는 순서로 인지하지 않고 이름으로 인지한다.
# 단순변수
def sum(f,s):
  first= s  
  second = f
  result= first + second
  return result,second,first #순서를 받기 위해 순서를 지정한다

In [50]:
sum(4,5)

9

In [ ]:
#조종하기 위해 변수에 담는다
r= sum(4,5)
r

In [66]:
# `_`변수는 리턴값을 사용하지 않을 때 사용
_, r02, r03 = sum(20,5) 
print(r02,r03)

20 5


In [55]:
def multi(a,b,c):
  one= a
  two = b
  three = c
  result = one*two*three
  return result

In [53]:
multi(21,32,2), multi(31,63,41)

(1344, 80073)

In [69]:
# def differenceVars(*var01, **args02)
def difparam(*var_list, **var_dict) : # 이 파라메터에 *는 list,**는 dictinary
  print(var_dict) # 프린트만시킴
  result01 = len(var_list)
  return result01

 * 리스트는 순서가 중요해 첫번째들어온값1, 두번째들어온값2,..,다섯번째들어온 값은 6이 됨

In [71]:
difparam(1,2,3,5,6,c=5,d=6,a=2,b=4)

{'c': 5, 'd': 6, 'a': 2, 'b': 4}


5

### function 만들기
1. function name 설정: 소통변수 무엇으로 하지?
2. 내부 어떻게 동작 해야해?
3. returen 결과값

연습
1. onehotcylinder(cylinders)
2. 1차원 행렬(onehot encoding)
3. if

In [72]:

def onehotcylinder(cylinders):  
  if cylinders == 3:
    cylinder=np.array([1,0,0,0,0])
  elif cylinders ==4:
    cylinder=np.array([0,1,0,0,0])
  elif cylinders == 5:
    cylinder=np.array([0,0,1,0,0])
  elif cylinders == 6:
    cylinder=np.array([0,0,0,1,0])
  else:
    cylinder=np.array([0,0,0,0,1])
  return cylinder


In [78]:
onehotcylinder(4)

array([0, 1, 0, 0, 0])

In [79]:
displacement=307.0
horsepower=130.0
weight=3504.0
accel=12.0
cylinders= 8
origin=1

x_continus =np.array([displacement,horsepower,weight,accel])
cylinder= onehotcylinder(cylinders)
org=np.array([1,0,0]) 

In [80]:
result= np.concatenate((x_continus,cylinder,org), axis=None)
result.shape,result 

((12,),
 array([3.070e+02, 1.300e+02, 3.504e+03, 1.200e+01, 0.000e+00, 0.000e+00,
        0.000e+00, 0.000e+00, 1.000e+00, 1.000e+00, 0.000e+00, 0.000e+00]))

In [82]:
result = result.reshape(-1, result.size)
result

array([[3.070e+02, 1.300e+02, 3.504e+03, 1.200e+01, 0.000e+00, 0.000e+00,
        0.000e+00, 0.000e+00, 1.000e+00, 1.000e+00, 0.000e+00, 0.000e+00]])