<a href="https://colab.research.google.com/github/ginttone/multi_python/blob/master/5_test_KFold.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

KFold<br> 
내가 넣은 숫자만큼 쪼개줌

class sklearn.model_selection.KFold(n_splits=5, *, shuffle=False, random_state=None)

X.shape#feature , y.shape #label

In [6]:
import numpy as np
X = np.array([[1, 2], [3, 4], [1, 2], [3, 4],[5,6],[7,8],[9,10]])
y = np.array([1, 2, 3, 4, 2, 3, 1])
X.shape , y.shape 

((7, 2), (7,))

In [12]:
from sklearn.model_selection import KFold
KF= KFold(n_splits=2,shuffle=True)
KF.get_n_splits(X)

2

실제 데이터 넣어서 스플릿 해보기

결과: np.array 한 행의 위치값이 나온 것 


In [15]:
for first, second in KF.split(X):
  print(first,':',second)
  

[0 2 5] : [1 3 4 6]
[1 3 4 6] : [0 2 5]


데이터에 의한 쏠림을 줄여주려고 만듬
(overfit 줄이고자)

중복 안되게 서로 섞어진 것을 확인 가능

In [17]:
KF= KFold(n_splits=3,shuffle=True)
KF.get_n_splits(X)

for first, second in KF.split(X):
  print(first,':',second)


[2 4 5 6] : [0 1 3]
[0 1 3 4 6] : [2 5]
[0 1 2 3 5] : [4 6]


mask씌우면 해당 값 찾을수 있어

first,second의 type은 np.ndarray로 되있음

shape은 (5,)(2,)

In [24]:
for first, second in KF.split(X):
  print(first,':',second)
  print('---------')
  x_train=X[first]
  print(x_train)
  print('---------')
  x_test = X[second]
  print(x_test)

[0 1 3 5] : [2 4 6]
---------
[[1 2]
 [3 4]
 [3 4]
 [7 8]]
---------
[[ 1  2]
 [ 5  6]
 [ 9 10]]
[0 2 3 4 6] : [1 5]
---------
[[ 1  2]
 [ 1  2]
 [ 3  4]
 [ 5  6]
 [ 9 10]]
---------
[[3 4]
 [7 8]]
[1 2 4 5 6] : [0 3]
---------
[[ 3  4]
 [ 1  2]
 [ 5  6]
 [ 7  8]
 [ 9 10]]
---------
[[1 2]
 [3 4]]
